apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx-app
  template:
    metadata:
      labels:
        app: php-nginx-app
    spec:
      containers:
        - name: app
          image: ringkokabiraj/nginx-php-app:latest
          ports:
            - containerPort: 80
         