apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
spec:
  selector:
    app: php-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to "LoadBalancer" on cloud providers
