name: Build and Deploy to Self-Hosted Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:  # 👈 this is the job ID
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fix Buildx Permissions (temporary workaround)
        run: |
         chmod +x /tmp/docker-actions-toolkit-*/buildx-bin-standalone/buildx || true

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/php-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/php-app:latest

  implement:  # 👈 job ID must be lowercase (recommended)
    name: Deploy to Self-Hosted Kubernetes
    needs: deploy  # 👈 refer to the job ID above
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
            set -e
            kubectl apply -f k8s/mysql-deployment.yaml || echo "No MySQL deployment found"
            kubectl apply -f k8s/mysql-service.yaml || echo "No MySQL service found"
            kubectl apply -f k8s/php-deployment.yaml || echo "No PHP deployment found"
            kubectl apply -f k8s/php-service.yaml || echo "No PHP service found"